#!/usr/bin/env bash

__version() {
  echo -e "\n${txtbld}deliver v$VERSION$txtrst | $HOMEPAGE\n"
  exit 0
}

while (( $# ))
do
  parameter="$1" && shift
  case "${parameter}" in
    (-D|--debug)
      set -x
      ;;
    (-V|--verbose)
      VERBOSE=true
      SILENCE="" 
      ;;
    (-v|--version)
      __version 
      ;;
    (*)
      echo "Unknown parameter ${parameter} ignored."
      ;;
  esac
done
